package event;

import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dobir
 */
public class BuyTicketsUserInterface extends javax.swing.JFrame {

    /**
     * Creates new form BuyTicketsUserInterface
     */
    public BuyTicketsUserInterface() {
        initComponents();
    }
    
    public BuyTicketsUserInterface(String value) {
        initComponents();
        
        BuyButton.setEnabled(false);
        
        String eventName = value.substring(0, value.indexOf(" | "));
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("events.txt"));
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(" / ");
                if (parts[1].trim().equals(eventName.trim())) {
                    SelectedEventBuyField.setText(parts[1]);
                    CountryBuyField.setText(parts[5]);
                    CityBuyField.setText(parts[6]);
                    AddressBuyField.setText(parts[7]);
                    DateOfEventBuyField.setText(parts[3]);
                    TicketsAvailableBuyField.setText(parts[9]);
                    PriceOfTicketsBuyField.setText(parts[8]);
                }
            }
            br.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        NumberOfTicketsToBuy.setModel(new javax.swing.SpinnerNumberModel(1, 1, Integer.parseInt(TicketsAvailableBuyField.getText()), 1));
        TotalBuyField.setText((Integer) NumberOfTicketsToBuy.getValue() * Integer.parseInt(PriceOfTicketsBuyField.getText()) + " Lei");
        
        area.setText("                      --------------------------------------------------------------\n\n");
        
        area.setText(area.getText() + "                                                    Receipt\n");
        area.setText(area.getText() + "\n                      --------------------------------------------------------------\n\n\n");
        
        Date obj = new Date();
        String date = obj.toString();

        area.setText(area.getText() + "                      Event: " + SelectedEventBuyField.getText() + "\n\n");
        area.setText(area.getText() + "                      Country and city: " + CountryBuyField.getText() + " " + CityBuyField.getText() + "\n\n");
        area.setText(area.getText() + "                      Location: " + AddressBuyField.getText() + "\n\n");
        area.setText(area.getText() + "                      Tickets:                                                  " + PriceOfTicketsBuyField.getText() + "  x" + NumberOfTicketsToBuy.getValue() + "");

        area.setText(area.getText() + "\n\n\n                      --------------------------------------------------------------\n\n");
        area.setText(area.getText() + "                      Total:                                                      " + TotalBuyField.getText());
        area.setText(area.getText() + "\n\n                      --------------------------------------------------------------");
        area.setText(area.getText() + "\n\n\n               " + date + "              Signature: " + UserInterface.UsernameLabel.getText());  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuyButton = new javax.swing.JButton();
        PriceOfTicketsBuyLabel = new javax.swing.JLabel();
        PriceOfTicketsBuyField = new javax.swing.JTextField();
        TicketsAvailableBuyLabel = new javax.swing.JLabel();
        TicketsAvailableBuyField = new javax.swing.JTextField();
        DateOfTheEventBuyLabel = new javax.swing.JLabel();
        DateOfEventBuyField = new javax.swing.JTextField();
        AddressBuyLabel = new javax.swing.JLabel();
        AddressBuyField = new javax.swing.JTextField();
        CountryBuyLabel = new javax.swing.JLabel();
        CountryBuyField = new javax.swing.JTextField();
        CityBuyField = new javax.swing.JTextField();
        CityBuyLabel = new javax.swing.JLabel();
        SelectedEventBuyField = new javax.swing.JTextField();
        SelectedEventBuyLabel = new javax.swing.JLabel();
        BuyTicketsLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        NoOfTicketsBuyLabel = new javax.swing.JLabel();
        NumberOfTicketsToBuy = new javax.swing.JSpinner();
        TotalBuyLabel = new javax.swing.JLabel();
        TotalBuyField = new javax.swing.JTextField();
        ConfirmPurchaseBox = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        BuyButton.setBackground(new java.awt.Color(0, 153, 153));
        BuyButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BuyButton.setForeground(new java.awt.Color(255, 255, 255));
        BuyButton.setText("Buy");
        BuyButton.setToolTipText("");
        BuyButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BuyButton.setBorderPainted(false);
        BuyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyButtonActionPerformed(evt);
            }
        });

        PriceOfTicketsBuyLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PriceOfTicketsBuyLabel.setForeground(new java.awt.Color(0, 102, 102));
        PriceOfTicketsBuyLabel.setText("Price of the tickets:");

        PriceOfTicketsBuyField.setEditable(false);
        PriceOfTicketsBuyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceOfTicketsBuyFieldActionPerformed(evt);
            }
        });

        TicketsAvailableBuyLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TicketsAvailableBuyLabel.setForeground(new java.awt.Color(0, 102, 102));
        TicketsAvailableBuyLabel.setText("Tickets available:");

        TicketsAvailableBuyField.setEditable(false);

        DateOfTheEventBuyLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DateOfTheEventBuyLabel.setForeground(new java.awt.Color(0, 102, 102));
        DateOfTheEventBuyLabel.setText("Date of the event:");

        DateOfEventBuyField.setEditable(false);

        AddressBuyLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AddressBuyLabel.setForeground(new java.awt.Color(0, 102, 102));
        AddressBuyLabel.setText("Address:");

        AddressBuyField.setEditable(false);
        AddressBuyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressBuyFieldActionPerformed(evt);
            }
        });

        CountryBuyLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CountryBuyLabel.setForeground(new java.awt.Color(0, 102, 102));
        CountryBuyLabel.setText("Country:");

        CountryBuyField.setEditable(false);
        CountryBuyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryBuyFieldActionPerformed(evt);
            }
        });

        CityBuyField.setEditable(false);
        CityBuyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityBuyFieldActionPerformed(evt);
            }
        });

        CityBuyLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CityBuyLabel.setForeground(new java.awt.Color(0, 102, 102));
        CityBuyLabel.setText("City:");

        SelectedEventBuyField.setEditable(false);
        SelectedEventBuyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectedEventBuyFieldActionPerformed(evt);
            }
        });

        SelectedEventBuyLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SelectedEventBuyLabel.setForeground(new java.awt.Color(0, 102, 102));
        SelectedEventBuyLabel.setText("Selected event:");

        BuyTicketsLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        BuyTicketsLabel.setForeground(new java.awt.Color(0, 102, 102));
        BuyTicketsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BuyTicketsLabel.setText("Buy tickets");
        BuyTicketsLabel.setFocusable(false);

        NoOfTicketsBuyLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NoOfTicketsBuyLabel.setForeground(new java.awt.Color(0, 102, 102));
        NoOfTicketsBuyLabel.setText("How many tickes you want to buy:");

        NumberOfTicketsToBuy.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NumberOfTicketsToBuy.setToolTipText("");
        NumberOfTicketsToBuy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NumberOfTicketsToBuyStateChanged(evt);
            }
        });

        TotalBuyLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TotalBuyLabel.setForeground(new java.awt.Color(0, 102, 102));
        TotalBuyLabel.setText("Your total:");

        TotalBuyField.setEditable(false);
        TotalBuyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalBuyFieldActionPerformed(evt);
            }
        });

        ConfirmPurchaseBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ConfirmPurchaseBox.setForeground(new java.awt.Color(0, 102, 102));
        ConfirmPurchaseBox.setText("Confirm your purchase");
        ConfirmPurchaseBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPurchaseBoxActionPerformed(evt);
            }
        });

        area.setEditable(false);
        area.setColumns(20);
        area.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        area.setForeground(new java.awt.Color(0, 102, 102));
        area.setRows(5);
        area.setAutoscrolls(false);
        area.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jScrollPane1.setViewportView(area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BuyTicketsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ConfirmPurchaseBox)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(CountryBuyLabel)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(CountryBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(24, 24, 24)
                                                        .addComponent(CityBuyLabel)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(CityBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(SelectedEventBuyLabel)
                                                        .addGap(34, 34, 34)
                                                        .addComponent(SelectedEventBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(PriceOfTicketsBuyLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(PriceOfTicketsBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(6, 6, 6))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(DateOfTheEventBuyLabel)
                                                            .addComponent(TicketsAvailableBuyLabel)
                                                            .addComponent(AddressBuyLabel))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(AddressBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(TicketsAvailableBuyField)
                                                                .addComponent(DateOfEventBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addComponent(BuyButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(TotalBuyLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(TotalBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(NoOfTicketsBuyLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(NumberOfTicketsToBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 44, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BuyTicketsLabel)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SelectedEventBuyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectedEventBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CountryBuyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CountryBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CityBuyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CityBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressBuyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddressBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DateOfTheEventBuyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateOfEventBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TicketsAvailableBuyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TicketsAvailableBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PriceOfTicketsBuyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriceOfTicketsBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NoOfTicketsBuyLabel)
                            .addComponent(NumberOfTicketsToBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalBuyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalBuyField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)))
                .addComponent(ConfirmPurchaseBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BuyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BuyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyButtonActionPerformed
        BuyButton.setEnabled(false);
        int value = Integer.parseInt(TicketsAvailableBuyField.getText()) - (Integer) NumberOfTicketsToBuy.getValue();
        Event.substractTickets(Integer.parseInt(TicketsAvailableBuyField.getText()), value);
        try {
            area.print();
        } catch (PrinterException ex) {
            Logger.getLogger(BuyTicketsUserInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        JOptionPane.showMessageDialog(null, "Purchase complete!");
        
    }//GEN-LAST:event_BuyButtonActionPerformed

    private void AddressBuyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressBuyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressBuyFieldActionPerformed

    private void CountryBuyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryBuyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountryBuyFieldActionPerformed

    private void CityBuyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityBuyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityBuyFieldActionPerformed

    private void SelectedEventBuyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectedEventBuyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectedEventBuyFieldActionPerformed

    private void ConfirmPurchaseBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPurchaseBoxActionPerformed
        if(ConfirmPurchaseBox.isSelected()){
            BuyButton.setEnabled(true);
        }else{
            BuyButton.setEnabled(false);
        }
    }//GEN-LAST:event_ConfirmPurchaseBoxActionPerformed

    private void TotalBuyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalBuyFieldActionPerformed

    }//GEN-LAST:event_TotalBuyFieldActionPerformed

    private void NumberOfTicketsToBuyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NumberOfTicketsToBuyStateChanged

        Integer myInt = (Integer) NumberOfTicketsToBuy.getValue() * Integer.parseInt(PriceOfTicketsBuyField.getText());
        String spinner = myInt.toString();
        TotalBuyField.setText(spinner + " Lei");
        area.setText(null);
        area.setText("                      --------------------------------------------------------------\n\n");
        
        area.setText(area.getText() + "                                                    Receipt\n");
        area.setText(area.getText() + "\n                      --------------------------------------------------------------\n\n\n");
        
        Date obj = new Date();
        String date = obj.toString();

        area.setText(area.getText() + "                      Event: " + SelectedEventBuyField.getText() + "\n\n");
        area.setText(area.getText() + "                      Country and city: " + CountryBuyField.getText() + " " + CityBuyField.getText() + "\n\n");
        area.setText(area.getText() + "                      Location: " + AddressBuyField.getText() + "\n\n");
        area.setText(area.getText() + "                      Tickets:                                                  " + PriceOfTicketsBuyField.getText() + "  x" + NumberOfTicketsToBuy.getValue() + "");

        area.setText(area.getText() + "\n\n\n                      --------------------------------------------------------------\n\n");
        area.setText(area.getText() + "                      Total:                                                      " + TotalBuyField.getText());
        area.setText(area.getText() + "\n\n                      --------------------------------------------------------------");
        area.setText(area.getText() + "\n\n\n               " + date + "              Signature: " + UserInterface.UsernameLabel.getText());    
        
    }//GEN-LAST:event_NumberOfTicketsToBuyStateChanged

    private void PriceOfTicketsBuyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceOfTicketsBuyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceOfTicketsBuyFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyTicketsUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyTicketsUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyTicketsUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyTicketsUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyTicketsUserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressBuyField;
    private javax.swing.JLabel AddressBuyLabel;
    private javax.swing.JButton BuyButton;
    private javax.swing.JLabel BuyTicketsLabel;
    private javax.swing.JTextField CityBuyField;
    private javax.swing.JLabel CityBuyLabel;
    private javax.swing.JCheckBox ConfirmPurchaseBox;
    private javax.swing.JTextField CountryBuyField;
    private javax.swing.JLabel CountryBuyLabel;
    private javax.swing.JTextField DateOfEventBuyField;
    private javax.swing.JLabel DateOfTheEventBuyLabel;
    private javax.swing.JLabel NoOfTicketsBuyLabel;
    private javax.swing.JSpinner NumberOfTicketsToBuy;
    private javax.swing.JTextField PriceOfTicketsBuyField;
    private javax.swing.JLabel PriceOfTicketsBuyLabel;
    private javax.swing.JTextField SelectedEventBuyField;
    private javax.swing.JLabel SelectedEventBuyLabel;
    private javax.swing.JTextField TicketsAvailableBuyField;
    private javax.swing.JLabel TicketsAvailableBuyLabel;
    private javax.swing.JTextField TotalBuyField;
    private javax.swing.JLabel TotalBuyLabel;
    private javax.swing.JTextArea area;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
