package event;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dobir
 */
public class SignUpWindow extends javax.swing.JFrame {

    /**
     * Creates new form SignUpWindow
     */
    public SignUpWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        SignUpLabel = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        SignInButton = new javax.swing.JButton();
        SelectEventLabel = new javax.swing.JLabel();
        FestivalCheckBox = new javax.swing.JCheckBox();
        MovieCheckBox = new javax.swing.JCheckBox();
        ArtCheckBox = new javax.swing.JCheckBox();
        ConcertCheckBox = new javax.swing.JCheckBox();
        CategoriesLabel = new javax.swing.JLabel();
        OtherCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setMaximumSize(new java.awt.Dimension(395, 432));
        setMinimumSize(new java.awt.Dimension(395, 432));
        setName("SignUpWindow"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(395, 432));

        jSeparator3.setMinimumSize(new java.awt.Dimension(50, 10));
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 10));

        SignUpLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        SignUpLabel.setForeground(new java.awt.Color(0, 102, 102));
        SignUpLabel.setText("Sign up");

        EmailField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EmailField.setForeground(new java.awt.Color(0, 102, 102));
        EmailField.setText("E-mail");
        EmailField.setToolTipText("Enter your e-mail address");
        EmailField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        EmailField.setMinimumSize(new java.awt.Dimension(64, 20));
        EmailField.setPreferredSize(new java.awt.Dimension(60, 20));
        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });

        PasswordField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(0, 102, 102));
        PasswordField.setText("Password");
        PasswordField.setToolTipText("Enter your password");
        PasswordField.setActionCommand("<Not Set>");
        PasswordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Already have an account?");

        RegisterButton.setBackground(new java.awt.Color(0, 153, 153));
        RegisterButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Register");
        RegisterButton.setToolTipText("");
        RegisterButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RegisterButton.setBorderPainted(false);
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        SignInButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        SignInButton.setForeground(new java.awt.Color(0, 102, 102));
        SignInButton.setText("Sign in");
        SignInButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SignInButton.setBorderPainted(false);
        SignInButton.setMaximumSize(new java.awt.Dimension(46, 18));
        SignInButton.setMinimumSize(new java.awt.Dimension(46, 18));
        SignInButton.setOpaque(true);
        SignInButton.setPreferredSize(new java.awt.Dimension(46, 18));
        SignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButtonActionPerformed(evt);
            }
        });

        SelectEventLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SelectEventLabel.setForeground(new java.awt.Color(0, 102, 102));
        SelectEventLabel.setText("Select your prefered type of events:");

        FestivalCheckBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FestivalCheckBox.setText("Festival");

        MovieCheckBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        MovieCheckBox.setText("Movie");

        ArtCheckBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ArtCheckBox.setText("Art");
        ArtCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArtCheckBoxActionPerformed(evt);
            }
        });

        ConcertCheckBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ConcertCheckBox.setText("Concert");
        ConcertCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcertCheckBoxActionPerformed(evt);
            }
        });

        CategoriesLabel.setBackground(new java.awt.Color(0, 102, 102));
        CategoriesLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CategoriesLabel.setForeground(new java.awt.Color(0, 102, 102));
        CategoriesLabel.setText("Categories:");

        OtherCheckBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        OtherCheckBox.setText("Other");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(SignUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CategoriesLabel)
                                .addGap(1, 1, 1)
                                .addComponent(ConcertCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ArtCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MovieCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FestivalCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OtherCheckBox))
                            .addComponent(SelectEventLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RegisterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                            .addComponent(EmailField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(160, 160, 160)
                                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(SignInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(PasswordField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SignUpLabel)
                .addGap(40, 40, 40)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SelectEventLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CategoriesLabel)
                    .addComponent(ConcertCheckBox)
                    .addComponent(ArtCheckBox)
                    .addComponent(MovieCheckBox)
                    .addComponent(FestivalCheckBox)
                    .addComponent(OtherCheckBox))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SignInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed

        if(EmailField.getText().isEmpty() || PasswordField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all the forms!");
        }else{
            String email = EmailField.getText();
            String password = PasswordField.getText();
            int user = -1;
            
            if(MovieCheckBox.isSelected() || ArtCheckBox.isSelected() || ConcertCheckBox.isSelected() || FestivalCheckBox.isSelected() || OtherCheckBox.isSelected()){
                try {
                    user = Authentification.register(email, password);
                } catch (IOException ex) {
                    Logger.getLogger(SignUpWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (user>=0) {
                    
                    Authentification.userid = user;
                    
                    if(MovieCheckBox.isSelected()){
                        try {
                            User.addCategory(user, "Movie");
                        } catch (IOException ex) {
                            Logger.getLogger(SignUpWindow.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    if(ArtCheckBox.isSelected()){
                        try {
                            User.addCategory(user, "Art");
                        } catch (IOException ex) {
                            Logger.getLogger(SignUpWindow.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    if(ConcertCheckBox.isSelected()){
                        try {
                            User.addCategory(user, "Concert");
                        } catch (IOException ex) {
                            Logger.getLogger(SignUpWindow.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    if(FestivalCheckBox.isSelected()){
                        try {
                            User.addCategory(user, "Festival");
                        } catch (IOException ex) {
                            Logger.getLogger(SignUpWindow.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    
                    if(OtherCheckBox.isSelected()){
                        try {
                            User.addCategory(user, "Other");
                        } catch (IOException ex) {
                            Logger.getLogger(SignUpWindow.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    
                    JOptionPane.showMessageDialog(null, "Registration successful!");
                    dispose();
                    new LogInWindow().setVisible(true);

                }
            }else{
                JOptionPane.showMessageDialog(null, "Check at least one box");
            }
        }     
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed
        dispose();
        new LogInWindow().setVisible(true);
    }//GEN-LAST:event_SignInButtonActionPerformed

    private void ArtCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArtCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArtCheckBoxActionPerformed

    private void ConcertCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConcertCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConcertCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ArtCheckBox;
    private javax.swing.JLabel CategoriesLabel;
    private javax.swing.JCheckBox ConcertCheckBox;
    private javax.swing.JTextField EmailField;
    private javax.swing.JCheckBox FestivalCheckBox;
    private javax.swing.JCheckBox MovieCheckBox;
    private javax.swing.JCheckBox OtherCheckBox;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel SelectEventLabel;
    private javax.swing.JButton SignInButton;
    private javax.swing.JLabel SignUpLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
